In [1]:
from preprocessor import AzdiasPreprocessor, FeatureDropper, Encoder, MixedFeatureEngineer
from pprint import pprint
import pandas as pd

In [2]:
# preprocessor = AzdiasPreprocessor(
#     data_source="Udacity_AZDIAS_Subset.csv",
#     summary_source="AZDIAS_Feature_summary.csv",
#     na_feature_threshold=20,
#     na_sample_threshold=25
# )
# preprocessor

In [3]:
# Test One Hot Encoder
df_test_raw = pd.read_csv("Udacity_AZDIAS_Subset.csv", delimiter=";")

In [4]:
df_test_raw.head()

,AGER_TYP,ALTERSKATEGORIE_GROB,ANREDE_KZ,CJT_GESAMTTYP,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,...,PLZ8_ANTG1,PLZ8_ANTG2,PLZ8_ANTG3,PLZ8_ANTG4,PLZ8_BAUMAX,PLZ8_HHZ,PLZ8_GBZ,ARBEIT,ORTSGR_KLS9,RELAT_AB
0,-1,2,1,2.0,3,4,3,5,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-1,1,2,5.0,1,5,2,5,4,5,...,2.0,3.0,2.0,1.0,1.0,5.0,4.0,3.0,5.0,4.0
2,-1,3,2,3.0,1,4,1,2,3,5,...,3.0,3.0,1.0,0.0,1.0,4.0,4.0,3.0,5.0,2.0
3,2,4,2,2.0,4,2,5,2,1,2,...,2.0,2.0,2.0,0.0,1.0,3.0,4.0,2.0,3.0,3.0
4,-1,3,1,5.0,4,3,4,1,3,2,...,2.0,4.0,2.0,1.0,2.0,3.0,3.0,4.0,6.0,5.0

In [5]:
# df_test_1 = preprocessor.clean_data(df_test_raw)
# df_test_1.head()

In [6]:
df_test_ost = df_test_raw[['OST_WEST_KZ']]
df_test_ost.head()

  OST_WEST_KZ
0         NaN
1           W
2           W
3           W
4           W

In [7]:
ordinal_encoder = Encoder(
    ordinal_features=['OST_WEST_KZ'],
    onehot_features=[],
)

In [8]:
df_test_raw['OST_WEST_KZ'].value_counts()

OST_WEST_KZ
W    629528
O    168545
Name: count, dtype: int64

In [9]:
df_test_ost.value_counts()

OST_WEST_KZ
W              629528
O              168545
Name: count, dtype: int64

In [10]:
type(df_test_ost)
df_test_ost.head()

  OST_WEST_KZ
0         NaN
1           W
2           W
3           W
4           W

In [11]:
df_test_ost = ordinal_encoder.fit_transform(df_test_ost)
df_test_ost.head()

Encoder Fitting Ordinal Encoder...
onehot_features: []
ordinal_features: ['OST_WEST_KZ']
Encoder Creating and Fitting Ordinal Encoder...
Encoder Engineering Features...
Ordinal encoded 1 feature(s)
One-hot encoded 0 feature(s) into 0 features

   OST_WEST_KZ
0          NaN
1          1.0
2          1.0
3          1.0
4          1.0

In [12]:
df_test_ost.value_counts()

OST_WEST_KZ
1.0            629528
0.0            168545
Name: count, dtype: int64

In [13]:
df_test_onehot = df_test_raw[['CAMEO_DEU_2015']]
print(df_test_onehot.shape)
df_test_onehot.head()

(891221, 1)

  CAMEO_DEU_2015
0            NaN
1             8A
2             4C
3             2A
4             6B

In [14]:
print(f"df_test_onehot unique: {df_test_onehot['CAMEO_DEU_2015'].unique()}")
print(f"df_test_onehot count unique: {df_test_onehot['CAMEO_DEU_2015'].nunique()}")
print(df_test_onehot.isna().sum())
df_test_onehot.value_counts().sort_index()

df_test_onehot unique: [nan '8A' '4C' '2A' '6B' '8C' '4A' '2D' '1A' '1E' '9D' '5C' '8B' '7A' '5D'
 '9E' '9B' '1B' '3D' '4E' '4B' '3C' '5A' '7B' '9A' '6D' '6E' '2C' '7C'
 '9C' '7D' '5E' '1D' '8D' '6C' '6A' '5B' '4D' '3A' '2B' '7E' '3B' '6F'
 '5F' '1C' 'XX']
df_test_onehot count unique: 45
CAMEO_DEU_2015    98979
dtype: int64

CAMEO_DEU_2015
1A                10850
1B                 4071
1C                 4317
1D                11909
1E                 5065
2A                13249
2B                15486
2C                19422
2D                35074
3A                10543
3B                 7160
3C                34769
3D                34307
4A                33155
4B                 9047
4C                47819
4D                 8570
4E                 5321
5A                12214
5B                10354
5C                 9935
5D                14943
5E                 3581
5F                 4283
6A                 6810
6B                56672
6C                14820
6D                 6073
6E                16107
6F                 5392
7A                34399
7B                24503
7C                 9065
7D                 5333
7E                 4633
8A                52438
8B                33434
8C                30993
8D                17576
9A                20542
9B                27676
9C                24987
9D                28593
9E                 6379
XX                  373
Name: count, dtype: int64

In [15]:
onehot_encoder = Encoder(
    ordinal_features= [],
    onehot_features=['CAMEO_DEU_2015'],
)
onehot_encoder

Encoder(onehot_features=['CAMEO_DEU_2015'], ordinal_features=[])

In [16]:
df_test_onehot = onehot_encoder.fit_transform(df_test_onehot)
df_test_onehot.head()

Encoder Fitting Ordinal Encoder...
onehot_features: ['CAMEO_DEU_2015']
ordinal_features: []
Encoder Creating and Fitting Onehot Encoder...
Encoder Engineering Features...
Ordinal encoded 0 feature(s)
One-hot encoded 1 feature(s) into 46 features

,CAMEO_DEU_2015_1A,CAMEO_DEU_2015_1B,CAMEO_DEU_2015_1C,CAMEO_DEU_2015_1D,CAMEO_DEU_2015_1E,CAMEO_DEU_2015_2A,CAMEO_DEU_2015_2B,CAMEO_DEU_2015_2C,CAMEO_DEU_2015_2D,CAMEO_DEU_2015_3A,...,CAMEO_DEU_2015_8B,CAMEO_DEU_2015_8C,CAMEO_DEU_2015_8D,CAMEO_DEU_2015_9A,CAMEO_DEU_2015_9B,CAMEO_DEU_2015_9C,CAMEO_DEU_2015_9D,CAMEO_DEU_2015_9E,CAMEO_DEU_2015_XX,CAMEO_DEU_2015_nan
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
df_test_onehot.sum()

CAMEO_DEU_2015_1A     10850.0
CAMEO_DEU_2015_1B      4071.0
CAMEO_DEU_2015_1C      4317.0
CAMEO_DEU_2015_1D     11909.0
CAMEO_DEU_2015_1E      5065.0
CAMEO_DEU_2015_2A     13249.0
CAMEO_DEU_2015_2B     15486.0
CAMEO_DEU_2015_2C     19422.0
CAMEO_DEU_2015_2D     35074.0
CAMEO_DEU_2015_3A     10543.0
CAMEO_DEU_2015_3B      7160.0
CAMEO_DEU_2015_3C     34769.0
CAMEO_DEU_2015_3D     34307.0
CAMEO_DEU_2015_4A     33155.0
CAMEO_DEU_2015_4B      9047.0
CAMEO_DEU_2015_4C     47819.0
CAMEO_DEU_2015_4D      8570.0
CAMEO_DEU_2015_4E      5321.0
CAMEO_DEU_2015_5A     12214.0
CAMEO_DEU_2015_5B     10354.0
CAMEO_DEU_2015_5C      9935.0
CAMEO_DEU_2015_5D     14943.0
CAMEO_DEU_2015_5E      3581.0
CAMEO_DEU_2015_5F      4283.0
CAMEO_DEU_2015_6A      6810.0
CAMEO_DEU_2015_6B     56672.0
CAMEO_DEU_2015_6C     14820.0
CAMEO_DEU_2015_6D      6073.0
CAMEO_DEU_2015_6E     16107.0
CAMEO_DEU_2015_6F      5392.0
CAMEO_DEU_2015_7A     34399.0
CAMEO_DEU_2015_7B     24503.0
CAMEO_DEU_2015_7C      9065.0
CAMEO_DEU_2015_7D      5333.0
CAMEO_DEU_2015_7E      4633.0
CAMEO_DEU_2015_8A     52438.0
CAMEO_DEU_2015_8B     33434.0
CAMEO_DEU_2015_8C     30993.0
CAMEO_DEU_2015_8D     17576.0
CAMEO_DEU_2015_9A     20542.0
CAMEO_DEU_2015_9B     27676.0
CAMEO_DEU_2015_9C     24987.0
CAMEO_DEU_2015_9D     28593.0
CAMEO_DEU_2015_9E      6379.0
CAMEO_DEU_2015_XX       373.0
CAMEO_DEU_2015_nan    98979.0
dtype: float64

In [18]:
df_test_encode = df_test_raw[['OST_WEST_KZ', 'CAMEO_DEU_2015']]
df_test_encode.head()

  OST_WEST_KZ CAMEO_DEU_2015
0         NaN            NaN
1           W             8A
2           W             4C
3           W             2A
4           W             6B

In [19]:
df_test_encode['OST_WEST_KZ'].value_counts()

OST_WEST_KZ
W    629528
O    168545
Name: count, dtype: int64

In [20]:
df_test_encode['CAMEO_DEU_2015'].value_counts().sort_index()

CAMEO_DEU_2015
1A    10850
1B     4071
1C     4317
1D    11909
1E     5065
2A    13249
2B    15486
2C    19422
2D    35074
3A    10543
3B     7160
3C    34769
3D    34307
4A    33155
4B     9047
4C    47819
4D     8570
4E     5321
5A    12214
5B    10354
5C     9935
5D    14943
5E     3581
5F     4283
6A     6810
6B    56672
6C    14820
6D     6073
6E    16107
6F     5392
7A    34399
7B    24503
7C     9065
7D     5333
7E     4633
8A    52438
8B    33434
8C    30993
8D    17576
9A    20542
9B    27676
9C    24987
9D    28593
9E     6379
XX      373
Name: count, dtype: int64

In [21]:
encoder = Encoder(
    ordinal_features=['OST_WEST_KZ'],
    onehot_features=['CAMEO_DEU_2015'],
)
encoder

Encoder(onehot_features=['CAMEO_DEU_2015'], ordinal_features=['OST_WEST_KZ'])

In [22]:
df_test_encode_results = encoder.fit_transform(df_test_encode)
df_test_encode_results.head()

Encoder Fitting Ordinal Encoder...
onehot_features: ['CAMEO_DEU_2015']
ordinal_features: ['OST_WEST_KZ']
Encoder Creating and Fitting Ordinal Encoder...
Encoder Creating and Fitting Onehot Encoder...
Encoder Engineering Features...
Ordinal encoded 1 feature(s)
One-hot encoded 1 feature(s) into 46 features

,OST_WEST_KZ,CAMEO_DEU_2015_1A,CAMEO_DEU_2015_1B,CAMEO_DEU_2015_1C,CAMEO_DEU_2015_1D,CAMEO_DEU_2015_1E,CAMEO_DEU_2015_2A,CAMEO_DEU_2015_2B,CAMEO_DEU_2015_2C,CAMEO_DEU_2015_2D,...,CAMEO_DEU_2015_8B,CAMEO_DEU_2015_8C,CAMEO_DEU_2015_8D,CAMEO_DEU_2015_9A,CAMEO_DEU_2015_9B,CAMEO_DEU_2015_9C,CAMEO_DEU_2015_9D,CAMEO_DEU_2015_9E,CAMEO_DEU_2015_XX,CAMEO_DEU_2015_nan
0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
df_test_encode_results['OST_WEST_KZ'].value_counts()

OST_WEST_KZ
1.0    629528
0.0    168545
Name: count, dtype: int64

In [24]:
df_test_encode_results.loc[:, df_test_encode_results.columns != 'OST_WEST_KZ'].sum()

CAMEO_DEU_2015_1A     10850.0
CAMEO_DEU_2015_1B      4071.0
CAMEO_DEU_2015_1C      4317.0
CAMEO_DEU_2015_1D     11909.0
CAMEO_DEU_2015_1E      5065.0
CAMEO_DEU_2015_2A     13249.0
CAMEO_DEU_2015_2B     15486.0
CAMEO_DEU_2015_2C     19422.0
CAMEO_DEU_2015_2D     35074.0
CAMEO_DEU_2015_3A     10543.0
CAMEO_DEU_2015_3B      7160.0
CAMEO_DEU_2015_3C     34769.0
CAMEO_DEU_2015_3D     34307.0
CAMEO_DEU_2015_4A     33155.0
CAMEO_DEU_2015_4B      9047.0
CAMEO_DEU_2015_4C     47819.0
CAMEO_DEU_2015_4D      8570.0
CAMEO_DEU_2015_4E      5321.0
CAMEO_DEU_2015_5A     12214.0
CAMEO_DEU_2015_5B     10354.0
CAMEO_DEU_2015_5C      9935.0
CAMEO_DEU_2015_5D     14943.0
CAMEO_DEU_2015_5E      3581.0
CAMEO_DEU_2015_5F      4283.0
CAMEO_DEU_2015_6A      6810.0
CAMEO_DEU_2015_6B     56672.0
CAMEO_DEU_2015_6C     14820.0
CAMEO_DEU_2015_6D      6073.0
CAMEO_DEU_2015_6E     16107.0
CAMEO_DEU_2015_6F      5392.0
CAMEO_DEU_2015_7A     34399.0
CAMEO_DEU_2015_7B     24503.0
CAMEO_DEU_2015_7C      9065.0
CAMEO_DEU_2015_7D      5333.0
CAMEO_DEU_2015_7E      4633.0
CAMEO_DEU_2015_8A     52438.0
CAMEO_DEU_2015_8B     33434.0
CAMEO_DEU_2015_8C     30993.0
CAMEO_DEU_2015_8D     17576.0
CAMEO_DEU_2015_9A     20542.0
CAMEO_DEU_2015_9B     27676.0
CAMEO_DEU_2015_9C     24987.0
CAMEO_DEU_2015_9D     28593.0
CAMEO_DEU_2015_9E      6379.0
CAMEO_DEU_2015_XX       373.0
CAMEO_DEU_2015_nan    98979.0
dtype: float64

In [25]:
import numpy as np
# Features to engineer
PRA_JUG = 'PRAEGENDE_JUGENDJAHRE'
CAM_INT = 'CAMEO_INTL_2015'
WOHN = 'WOHNLAGE'
LP_LEB = 'LP_LEBENSPHASE_FEIN'

# Engineered (new) features
P_DECADE = 'PRAEGENDE_DECADE'
P_MOVEMENT = 'PRAEGENDE_MOVEMENT'

C_WEALTH = 'CAMEO_WEALTH'
C_LIFE = 'CAMEO_LIFESTAGE'

WOHN_QUAL = 'WOHN_NEIGHBORHOOD_QUALITY'
WOHN_RURAL = 'WOHN_IS_RURAL'
WOHN_BUILD = 'WOHN_NEW_BUILDING'

LP_STAGE = 'LP_LIFE_STAGE'
LP_INCOME = 'LP_INCOME_LEVEL'
LP_AGE = 'LP_AGE_CLASS'
LP_HOMEOWN = 'LP_IS_HOMEOWNER'
LP_INDEP = 'LP_IS_INDEPENDENT'

MAPPINGS = {
    PRA_JUG: {
        P_DECADE: {
            1: 1940, 2: 1940, 3: 1950, 4: 1950, 5: 1960, 6: 1960, 7: 1960, 8: 1970, 9: 1970, 10: 1980,
            11: 1980, 12: 1980, 13: 1980, 14: 1990, 15: 1990
        },
        P_MOVEMENT: {
            1: 1, 2: 0, 3: 1, 4: 0, 5: 1, 6: 0, 7: 0, 8: 1, 9: 0, 10: 1, 11: 0, 12: 1, 13: 0, 14: 1,
            15: 0
        }
    },
    CAM_INT: {
        C_WEALTH: lambda x: int(x) // 10 if pd.notna(x) and str(x).replace('-', '').isdigit() else np.nan,
        C_LIFE: lambda x: int(x) % 10 if pd.notna(x) and str(x).replace('-', '').isdigit() else np.nan
    },
    LP_LEB: {
        LP_STAGE: {
            # Single
            1: 1,  2: 1,  3: 1,  4: 1,  5: 1, 6: 1,  7: 1,  8: 1,  9: 1, 10: 1, 11: 1, 12: 1, 13: 1,
            # Couple
            14: 2, 15: 2, 16: 2, 17: 2, 18: 2, 19: 2, 20: 2,
            # Single Parent
            21: 3, 22: 3, 23: 3,
            # Family
            24: 4, 25: 4, 26: 4, 27: 4, 28: 4,
            # Multiperson
            29: 5, 30: 5, 31: 5, 32: 5, 33: 5, 34: 5, 35: 5, 36: 5, 37: 5, 38: 5, 39: 5, 40: 5,
        },
        LP_INCOME: {
            # Low Income
            1: 1,  2: 1,  5: 1,  6: 1, 14: 1, 15: 1, 21: 1, 24: 1, 29: 1, 31: 1,
            # Average Income
            3: 2,  4: 2,  7: 2,  8: 2, 16: 2, 22: 2, 25: 2, 30: 2, 32: 2,
            # High Income
            23: 3,
            # Wealthy
            10: 4, 18: 4,
            # Top Earner
            13: 5, 20: 5, 28: 5, 35: 5, 39: 5, 40: 5,
        },
        LP_INDEP: {
            9: 1, 17: 1, 26: 1, 33: 1, 36: 1,
        },
        LP_AGE: {
            # Younger age
            1: 1,  3: 1, 14: 1, 18: 1, 29: 1,
            30: 1, 33: 1, 34: 1, 35: 1,
            # Middle age
            2: 2,  4: 2, 39: 2,
            # Higher age
            13: 3, 15: 3, 16: 3, 19: 3,
            20: 3, 31: 3, 32: 3, 36: 3,
            # Advanced age
            5: 4,  7: 4, 11: 4, 37: 4,
            # Retirement age
            6: 5,  8: 5, 12: 5, 38: 5, 40: 5,
        },
        LP_HOMEOWN: {
            10: 1, 11: 1, 12: 1, 18: 1, 19: 1,
            27: 1, 34: 1, 37: 1, 38: 1,
        }
    },
    WOHN: {
        WOHN_QUAL: {
            1: 1,   # very good
            2: 2,   # good
            3: 3,   # average
            4: 4,   # poor
            5: 5,   # very poor
        },
        WOHN_RURAL: {7: 1, 8: 1},
        WOHN_BUILD: {8: 1}
    }
}

In [26]:
mixed_engineer = MixedFeatureEngineer(
    mappings=MAPPINGS
)
mixed_engineer

MixedFeatureEngineer(mappings={'CAMEO_INTL_2015': {'CAMEO_LIFESTAGE': <function <lambda> at 0x000001A3006E8040>,
                                                   'CAMEO_WEALTH': <function <lambda> at 0x000001A3006EB2E0>},
                               'LP_LEBENSPHASE_FEIN': {'LP_AGE_CLASS': {1: 1,
                                                                        2: 2,
                                                                        3: 1,
                                                                        4: 2,
                                                                        5: 4,
                                                                        6: 5,
                                                                        7: 4,
                                                                        8: 5,
                                                                        11: 4,
                                                                        12: 5,
                                                                        13: 3,
                                                                        14: 1,
                                                                        15: 3,
                                                                        16: 3,
                                                                        18: 1,
                                                                        19: 3,
                                                                        20: 3,
                                                                        29: 1,
                                                                        30: 1,
                                                                        31: 3,
                                                                        32: 3,
                                                                        33: 1,
                                                                        34: 1,
                                                                        35: 1,
                                                                        36: 3,
                                                                        37: 4,
                                                                        38: 5,
                                                                        39: 2,
                                                                        40: 5},
                                                       'LP_INCOME_...
                               'PRAEGENDE_JUGENDJAHRE': {'PRAEGENDE_DECADE': {1: 1940,
                                                                              2: 1940,
                                                                              3: 1950,
                                                                              4: 1950,
                                                                              5: 1960,
                                                                              6: 1960,
                                                                              7: 1960,
                                                                              8: 1970,
                                                                              9: 1970,
                                                                              10: 1980,
                                                                              11: 1980,
                                                                              12: 1980,
                                                                              13: 1980,
                                                                              14: 1990,
                                                                              15: 1990},
                                                         'PRAEGENDE_MOVEMENT': {1: 1,
                                                                                2: 0,
                                                                                3: 1,
                                                                                4: 0,
                                                                                5: 1,
                                                                                6: 0,
                                                                                7: 0,
                                                                                8: 1,
                                                                                9: 0,
                                                                                10: 1,
                                                                                11: 0,
                                                                                12: 1,
                                                                                13: 0,
                                                                                14: 1,
                                                                                15: 0}},
                               'WOHNLAGE': {'WOHN_IS_RURAL': {7: 1, 8: 1},
                                            'WOHN_NEIGHBORHOOD_QUALITY': {1: 1,
                                                                          2: 2,
                                                                          3: 3,
                                                                          4: 4,
                                                                          5: 5},
                                            'WOHN_NEW_BUILDING': {8: 1}}})

In [27]:
df_test_engineer = df_test_raw[[PRA_JUG, CAM_INT, WOHN, LP_LEB]]
df_test_engineer.head()

   PRAEGENDE_JUGENDJAHRE CAMEO_INTL_2015  WOHNLAGE  LP_LEBENSPHASE_FEIN
0                      0             NaN       NaN                 15.0
1                     14              51       4.0                 21.0
2                     15              24       2.0                  3.0
3                      8              12       7.0                  0.0
4                      8              43       3.0                 32.0

In [28]:
for feature in df_test_engineer.columns:
    print(df_test_engineer[feature].value_counts().sort_index())

PRAEGENDE_JUGENDJAHRE
0     108164
1      21282
2       7479
3      55195
4      20451
5      86416
6      25652
7       4010
8     145988
9      33570
10     85808
11     35752
12     24446
13      5764
14    188697
15     42547
Name: count, dtype: int64
CAMEO_INTL_2015
12     13249
13     26336
14     62884
15     16974
22     33155
23     26750
24     91158
25     39628
31     19024
32     10354
33      9935
34     18524
35     10356
41     92336
43     56672
44     14820
45     26132
51    133694
52     20542
54     45391
55     23955
XX       373
Name: count, dtype: int64
WOHNLAGE
0.0      6950
1.0     43918
2.0    100376
3.0    249719
4.0    135973
5.0     74346
7.0    169318
8.0     17473
Name: count, dtype: int64
LP_LEBENSPHASE_FEIN
0.0     92778
1.0     62667
2.0     39434
3.0     19985
4.0     17595
5.0     55542
6.0     45614
7.0     26508
8.0     30475
9.0     13066
10.0    25789
11.0    26710
12.0    23300
13.0    26085
14.0    17529
15.0    20062
16.0    14466
17.0     5888
18.0     7168
19.0    19484
20.0    17132
21.0    12766
22.0     7224
23.0     9191
24.0    12091
25.0    10370
26.0     3584
27.0    14475
28.0    12264
29.0    26577
30.0    22361
31.0    23987
32.0    17105
33.0     6066
34.0    13074
35.0    13679
36.0    10505
37.0    18525
38.0    13914
39.0    16182
40.0    15150
Name: count, dtype: int64

In [29]:
df_test_engineered = mixed_engineer.fit_transform(df_test_engineer)
df_test_engineered.head()

MixedFeatureEngineer Encoding...features IN: ['CAMEO_INTL_2015', 'LP_LEBENSPHASE_FEIN', 'PRAEGENDE_JUGENDJAHRE', 'WOHNLAGE']
MixedFeatureEngineer Encoding...
MixedFeatureEngineer Encoded PRAEGENDE_DECADE from PRAEGENDE_JUGENDJAHRE
MixedFeatureEngineer Encoded PRAEGENDE_MOVEMENT from PRAEGENDE_JUGENDJAHRE
MixedFeatureEngineer Dropped PRAEGENDE_JUGENDJAHRE
MixedFeatureEngineer Encoded CAMEO_WEALTH from CAMEO_INTL_2015
MixedFeatureEngineer Encoded CAMEO_LIFESTAGE from CAMEO_INTL_2015
MixedFeatureEngineer Dropped CAMEO_INTL_2015
MixedFeatureEngineer Encoded LP_LIFE_STAGE from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_INCOME_LEVEL from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_IS_INDEPENDENT from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_AGE_CLASS from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_IS_HOMEOWNER from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Dropped LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded WOHN_NEIGHBORHOOD_QUALITY from WOHNLAGE
MixedFeatureEngineer Encoded WOHN_IS_RURAL from WOHNLAGE
MixedFeatureEngineer Encoded WOHN_NEW_BUILDING from WOHNLAGE
MixedFeatureEngineer Dropped WOHNLAGE
MixedFeatureEngineer Encoding...features OUT[1]: []
MixedFeatureEngineer Encoding...features OUT[2]: ['PRAEGENDE_DECADE', 'PRAEGENDE_MOVEMENT', 'CAMEO_WEALTH', 'CAMEO_LIFESTAGE', 'LP_LIFE_STAGE', 'LP_INCOME_LEVEL', 'LP_IS_INDEPENDENT', 'LP_AGE_CLASS', 'LP_IS_HOMEOWNER', 'WOHN_NEIGHBORHOOD_QUALITY', 'WOHN_IS_RURAL', 'WOHN_NEW_BUILDING']
MixedFeatureEngineer Encoding...features OUT[1]: []
MixedFeatureEngineer Encoding...features OUT[2]: ['PRAEGENDE_DECADE', 'PRAEGENDE_MOVEMENT', 'CAMEO_WEALTH', 'CAMEO_LIFESTAGE', 'LP_LIFE_STAGE', 'LP_INCOME_LEVEL', 'LP_IS_INDEPENDENT', 'LP_AGE_CLASS', 'LP_IS_HOMEOWNER', 'WOHN_NEIGHBORHOOD_QUALITY', 'WOHN_IS_RURAL', 'WOHN_NEW_BUILDING']

,PRAEGENDE_DECADE,PRAEGENDE_MOVEMENT,CAMEO_WEALTH,CAMEO_LIFESTAGE,LP_LIFE_STAGE,LP_INCOME_LEVEL,LP_IS_INDEPENDENT,LP_AGE_CLASS,LP_IS_HOMEOWNER,WOHN_NEIGHBORHOOD_QUALITY,WOHN_IS_RURAL,WOHN_NEW_BUILDING
0,NaN,NaN,NaN,NaN,2.0,1.0,NaN,3.0,NaN,NaN,NaN,NaN
1,1990.0,1.0,5.0,1.0,3.0,1.0,NaN,NaN,NaN,4.0,NaN,NaN
2,1990.0,0.0,2.0,4.0,1.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN
3,1970.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,1970.0,1.0,4.0,3.0,5.0,2.0,NaN,3.0,NaN,3.0,NaN,NaN

In [30]:
for feature in df_test_engineered.columns:
    print(df_test_engineered[feature].value_counts().sort_index())

PRAEGENDE_DECADE
1940.0     28761
1950.0     75646
1960.0    116078
1970.0    179558
1980.0    151770
1990.0    231244
Name: count, dtype: int64
PRAEGENDE_MOVEMENT
0.0    175225
1.0    607832
Name: count, dtype: int64
CAMEO_WEALTH
1.0    119443
2.0    190691
3.0     68193
4.0    189960
5.0    223582
Name: count, dtype: int64
CAMEO_LIFESTAGE
1.0    245054
2.0     77300
3.0    119693
4.0    232777
5.0    117045
Name: count, dtype: int64
LP_LIFE_STAGE
1.0    412770
2.0    101729
3.0     29181
4.0     52784
5.0    197125
Name: count, dtype: int64
LP_INCOME_LEVEL
1.0    316269
2.0    166089
3.0      9191
4.0     32957
5.0    100492
Name: count, dtype: int64
LP_IS_INDEPENDENT
1.0    39109
Name: count, dtype: int64
LP_AGE_CLASS
1.0    189106
2.0     73211
3.0    148826
4.0    127285
5.0    128453
Name: count, dtype: int64
LP_IS_HOMEOWNER
1.0    162439
Name: count, dtype: int64
WOHN_NEIGHBORHOOD_QUALITY
1.0     43918
2.0    100376
3.0    249719
4.0    135973
5.0     74346
Name: count, dtype: int64
WOHN_IS_RURAL
1.0    186791
Name: count, dtype: int64
WOHN_NEW_BUILDING
1.0    17473
Name: count, dtype: int64

In [31]:
# Test the mapping directly
test_series = pd.Series([1, 2, 9, 17, 26, 33, 36])
mapping = {9: 1, 17: 1, 26: 1, 33: 1, 36: 1}

result = test_series.map(MAPPINGS[LP_LEB][LP_INDEP])
print(result)
# Should show: NaN, NaN, 1.0, 1.0, 1.0, 1.0, 1.0

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
dtype: float64