In [1]:
from preprocessor import AzdiasPreprocessor, FeatureDropper, Encoder
from pprint import pprint
import pandas as pd

In [2]:
# preprocessor = AzdiasPreprocessor(
#     data_source="Udacity_AZDIAS_Subset.csv",
#     summary_source="AZDIAS_Feature_summary.csv",
#     na_feature_threshold=20,
#     na_sample_threshold=25
# )
# preprocessor

In [3]:
# Test One Hot Encoder
df_test_raw = pd.read_csv("Udacity_AZDIAS_Subset.csv", delimiter=";")

In [4]:
df_test_raw.head()

,AGER_TYP,ALTERSKATEGORIE_GROB,ANREDE_KZ,CJT_GESAMTTYP,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,...,PLZ8_ANTG1,PLZ8_ANTG2,PLZ8_ANTG3,PLZ8_ANTG4,PLZ8_BAUMAX,PLZ8_HHZ,PLZ8_GBZ,ARBEIT,ORTSGR_KLS9,RELAT_AB
0,-1,2,1,2.0,3,4,3,5,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-1,1,2,5.0,1,5,2,5,4,5,...,2.0,3.0,2.0,1.0,1.0,5.0,4.0,3.0,5.0,4.0
2,-1,3,2,3.0,1,4,1,2,3,5,...,3.0,3.0,1.0,0.0,1.0,4.0,4.0,3.0,5.0,2.0
3,2,4,2,2.0,4,2,5,2,1,2,...,2.0,2.0,2.0,0.0,1.0,3.0,4.0,2.0,3.0,3.0
4,-1,3,1,5.0,4,3,4,1,3,2,...,2.0,4.0,2.0,1.0,2.0,3.0,3.0,4.0,6.0,5.0

In [5]:
# df_test_1 = preprocessor.clean_data(df_test_raw)
# df_test_1.head()

In [6]:
df_test_ost = df_test_raw[['OST_WEST_KZ']]
df_test_ost.head()

  OST_WEST_KZ
0         NaN
1           W
2           W
3           W
4           W

In [7]:
ordinal_encoder = Encoder(
    ordinal_features=['OST_WEST_KZ'],
    onehot_features=[],
)

In [8]:
df_test_raw['OST_WEST_KZ'].value_counts()

OST_WEST_KZ
W    629528
O    168545
Name: count, dtype: int64

In [9]:
df_test_ost.value_counts()

OST_WEST_KZ
W              629528
O              168545
Name: count, dtype: int64

In [10]:
type(df_test_ost)
df_test_ost.head()

  OST_WEST_KZ
0         NaN
1           W
2           W
3           W
4           W

In [11]:
df_test_ost = ordinal_encoder.fit_transform(df_test_ost)
df_test_ost.head()

Encoder Fitting Ordinal Encoder...
onehot_features: []
ordinal_features: ['OST_WEST_KZ']
Encoder Creating and Fitting Ordinal Encoder...
Encoder Engineering Features...
Ordinal encoded 1 feature(s)
One-hot encoded 0 feature(s) into 0 features

   OST_WEST_KZ
0          NaN
1          1.0
2          1.0
3          1.0
4          1.0

In [12]:
df_test_ost.value_counts()

OST_WEST_KZ
1.0            629528
0.0            168545
Name: count, dtype: int64